AppBundle\Entity\Booking:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\BookingRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        visitDate:
            type: datetime
        bookingDate:
            type: datetime
        email:
            type: string
            length: 255
        code:
            type: string
            length: 255
    lifecycleCallbacks: {  }
